[project]
name = "gpt-telegram-bot"
version = "0.1.0"
description = ""
authors = [
    {name = "ecotalisman",email = "67708040+ecotalisman@users.noreply.github.com"}
]
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "openai (>=2.14.0,<3.0.0)",
    "python-telegram-bot (>=22.5,<23.0)",
    "python-dotenv (>=1.2.1,<2.0.0)",
    "aiosqlite (>=0.22.1,<0.23.0)",
    "aiofiles (>=25.1.0,<26.0.0)",
    "tabulate (>=0.9.0,<0.10.0)",
    "pydantic-settings (>=2.12.0,<3.0.0)"
]


[build-system]
requires = ["poetry-core>=2.0.0,<3.0.0"]
build-backend = "poetry.core.masonry.api"

[tool.poetry]
package-mode = false
